name: Render and Deploy KWB-R Package Status Table
on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - master
  schedule:
    # * is a special character in YAML so you have to quote this string
    # Run this job every day at 05:00 a.m UTC ('0 5 * * *')
    - cron:  '0 5 * * *'

jobs:
  render:
    runs-on: macOS-latest
    env: 
      ACTIONS_ALLOW_UNSECURE_COMMANDS: TRUE
      APPVEYOR_TOKEN: ${{ secrets.APPVEYOR_TOKEN }}
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}
      ZENODO_TOKEN: ${{ secrets.ZENODO_TOKEN }}
    steps:
      - uses: actions/checkout@v1
      - uses: r-lib/actions/setup-r@v1
      - uses: r-lib/actions/setup-pandoc@v1
      - name: Install rmarkdown, remotes, and the local package
        run: |
          install.packages("remotes")
          remotes::install_local(".")
        shell: Rscript {0}
      - name: Render Package Status Table
        run: Rscript -e "kwb.pkgstatus::create_report_rpackages()"
      - name: Commit results
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git commit index.html -m 'Re-build index.html'
          git push https://${{github.actor}}:${{secrets.GITHUB_TOKEN}}@github.com/${{github.repository}}.git HEAD:gh-pages
    container: rocker/verse:latest
