name: Render and Deploy KWB-R Package Status Table
on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - master
  schedule:
    # * is a special character in YAML so you have to quote this string
    # Run this job every day at 05:00 a.m UTC ('0 5 * * *')
    - cron:  '0 5 * * *'
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@master
      - name: Install Package Dependencies
        run: |-
          Rscript -e "install.packages('remotes', repos = 'https://demo.rstudiopm.com/all/__linux__/bionic/latest')"
          Rscript -e "remotes::install_deps(dependencies = TRUE, repos = 'https://demo.rstudiopm.com/all/__linux__/bionic/latest')"
      - name: Render Site
        run: |-
          Rscript -e "output_dir <- kwb.pkgstatus::create_report_rpackages()"
          echo "::set-env name=DEPLOY_PATH::$(Rscript -e "cat(output_dir)")"
      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/master'
        uses: maxheld83/ghpages@v0.2.0
        env:
          BUILD_DIR: $DEPLOY_PATH
          APPVEYOR_TOKEN: ${{ secrets.APPVEYOR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}
          ZENODO_TOKEN: ${{ secrets.ZENODO_TOKEN }}
    container: rocker/verse:latest
